name: Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
    group: ${{github.ref}}
    cancel-in-progress: true
    
env:
  # Secrets
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Variables
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  TF_VAR_region: ${{ vars.AWS_DEFAULT_REGION }}
  TF_VAR_bucket_name: ${{ vars.TF_VAR_bucket_name }}
  WORKING_DIR: live/dev


jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.5

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-init
          path: |
            ${{ env.WORKING_DIR }}/.terraform
            ${{ env.WORKING_DIR }}/terraform.lock.hcl


      - name: Terraform Validate
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform plan

      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main'
      #   working-directory: ${{ env.WORKING_DIR }}
      #   run: terraform apply -auto-approve