name: Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
    group: ${{github.ref}}
    cancel-in-progress: true

env:
  # Secrets
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Variables
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  TF_VAR_region: ${{ vars.AWS_DEFAULT_REGION }}
  TF_VAR_bucket_name: ${{ vars.TF_VAR_bucket_name }}
  WORKING_DIR: ./live/dev


jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.5

      - name: Terraform Init
        run: |
          terraform init

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-init-artifacts
          path: |
            .terraform.lock.hcl
            .terraform/

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
          out: tfsec-results.json
          format: json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-results
          path: tfsec-results.json

      - name: Terraform Plan
        run: |
          ls -la
          terraform plan -out=tfplan

      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main'
      #   run: terraform apply -auto-approve