name: Destroy Terraform
# TODO
on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  AWS_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  ROLE_ARN: ${{ vars.ROLE_ARN }}

jobs:
  terraform_destroy:
    name: Remove resources
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./live/dev

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.5

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan  -no-color -input=false

      - name: Terraform Destroy
        run: terraform destroy
